#! /bin/sh

# Call this without arguments if T8DG is the toplevel package.
# Call this with three arguments if T8DG is itself a subdirectory:
# ./bootstrap <sc config directory> <p4est config directory> <t8code config directory>

# RUNNING BOOTSTRAP FOR LIBSC

# override by option argument
SC_CONFIG="sc/config"
if test -n "$1" ; then
  SC_CONFIG="$1"
  if test ! -d "$SC_CONFIG" ; then
    echo "Cannot find directory $SC_CONFIG"
    exit 1
  fi
fi
# convert into an absolute path
SC_CONFIG=`cd "$SC_CONFIG" && pwd`

if test -x "sc/bootstrap" ; then
  echo "Running bootstrap in subdirectory sc"
  (cd sc && ./bootstrap)
fi

# RUNNING BOOTSTRAP FOR P4EST

#override by option argument
P4EST_CONFIG="p4est/config"
if test -n "$2" ; then
  P4EST_CONFIG="$2"
  if test ! -d "$P4EST_CONFIG" ; then
    echo "Cannot find directory $P4EST_CONFIG"
    exit 
  fi
fi
#convert into an absolute path
P4EST_CONFIG=`cd "$P4EST_CONFIG" && pwd`

if test -x "p4est/bootstrap" ; then
  echo "Running bootstrap in subdirectory p4est"
  (cd p4est && ./bootstrap "$SC_CONFIG")
fi

# RUNNING BOOTSTRAP FOR T8CODE

#override by option argument
T8_CONFIG="t8/config"
if test -n "$3" ; then
  T8_CONFIG="$3"
  if test ! -d "$T8_CONFIG" ; then
    echo "Cannot find directory $T8_CONFIG"
    exit 
  fi
fi
#convert into an absolute path
echo Changing to dir [$T8_CONFIG]
T8_CONFIG=`cd "$T8_CONFIG" && pwd`

if test -x "t8/bootstrap" ; then
  echo "Running bootstrap in subdirectory t8"
  (cd t8 && ./bootstrap "$SC_CONFIG" "$P4EST_CONFIG")
fi

# Starting now with t8dg part

echo "--- This is the bootstrap script for t8dg ---"
echo "Current directory is $PWD"

LIBTOOLIZE=`which glibtoolize`
if test ! -x "$LIBTOOLIZE" ; then LIBTOOLIZE=`which libtoolize` ; fi
if test ! -x "$LIBTOOLIZE" ; then echo "bootstrap requires libtoolize" ; \
   exit 1 ; fi

aclocal -Wall -I config -I "$SC_CONFIG" -I "$P4EST_CONFIG" -I "$T8_CONFIG"
autoconf -Wall --force
autoheader -Wall --force
"$LIBTOOLIZE" --install --copy
automake -Wall --add-missing --copy
