#!/bin/bash

# Change these entries to match your t8code library folder
BASEDIR=$HOME/t8code
T8_DIR=$BASEDIR/t8fixheader/local


# Compiler settings


# TODO: make a debug and a release version, maybe triggered with an command line argument
CC=mpicxx
CFLAGS='-Wall -pedantic -g'
SOURCE='../src/t8dg.c ../src/t8dg_quadrature.c ../src/t8dg_functionbasis.c
 ../src/t8dg_global_precomputed_values.c ../src/t8dg_local_precomputed_values.cxx
 ../src/t8dg_vertexset.c ../src/t8dg_timestepping.c ../src/t8dg_mortar.c
 ../src/t8dg_sc_array.c ../src/t8dg_coarse_geometry.c ../src/t8dg_flux.c 
 ../src/t8dg_advect_problem.cxx ../src/main.c'

# There should be no need to change the following lines
LIB=$T8_DIR/lib
INCLUDE=$T8_DIR/include

LIBS="-lt8 -lp4est -lsc -lm -lz"

export LD_LIBRARY_PATH=$LIB:$LD_LIBRARY_PATH

# compile line
echo libraries in $LIB
echo header in $INCLUDE

echo "$CC $CFLAGS -o t8dg $SOURCE -I$INCLUDE -I$INCLUDE/src -L$LIB $LIBS"
$CC $CFLAGS -o t8dg $SOURCE -I$INCLUDE -I$INCLUDE/src -L$LIB $LIBS
