#!/bin/bash

# Change these entries to match your t8code library folder
BASEDIR=$HOME/exec/t8code_debug
T8_DIR=$BASEDIR/install

# Folder containing the googletest library
GTEST_DIR=./lib
# Folder containing the googletest include files
GTEST_INCLUDE=../thirdparty/googletest

# Compiler settings


# TODO: make a debug and a release version, maybe triggered with an command line argument
CC=mpicxx
CFLAGS='-Wall -pedantic -g'
TESTCFLAGS='-pthread'
# The source files
SOURCE='../src/t8dg.c ../src/t8dg_quadrature.c ../src/t8dg_functionbasis.c
 ../src/t8dg_global_precomputed_values.c ../src/t8dg_local_precomputed_values.cxx
 ../src/t8dg_vertexset.c ../src/t8dg_timestepping.c ../src/t8dg_mortar.cxx
 ../src/t8dg_sc_array.c ../src/t8dg_coarse_geometry.c ../src/t8dg_flux.c 
 ../src/t8dg_advect_problem.cxx ../src/t8dg_refcount.c ../src/t8dg_dmatrix.c
 ../src/t8dg_precomputed_values.c ../src/t8dg_tensor.c ../src/t8dg_geometry.cxx'
 
# The source of the main program 
MAINSOURCE='../src/main.c'
# The sources of the tests and test main program
TESTSOURCE='../test/t8dg_test_main.cxx ../test/t8dg_test_timestepping.cxx ../test/t8dg_test_quadrature.cxx
  ../test/t8dg_test_dmatrix.cxx ../test/t8dg_test_functionbasis.cxx ../test/t8dg_test_precomputed_values.cxx'

# There should be no need to change the following lines
LIB_PATH="$T8_DIR/lib"
LIB="-L$LIB_PATH"
TESTLIB="-L$GTEST_DIR"
INCLUDE=$T8_DIR/include
TESTINCLUDE=$GTEST_INCLUDE

LIBS="-lt8 -lp4est -lsc -lm -lz -lopenblas"
# CBLASLIB="-L/usr/local/lib"
TESTLIBS="-lgtest"

export LD_LIBRARY_PATH=$LIB_PATH:$LD_LIBRARY_PATH

# compile line
echo libraries: $LIB
echo header in $INCLUDE

echo "$CC $CFLAGS -o t8dg $MAINSOURCE $SOURCE -I$INCLUDE -I$INCLUDE/src $LIB $LIBS"
$CC $CFLAGS -o t8dg $MAINSOURCE $SOURCE -I$INCLUDE -I$INCLUDE/src $LIB $LIBS

echo "$CC $CFLAGS $TESTCFLAGS -o t8dg_tests $TESTSOURCE $SOURCE -I../src -I$INCLUDE -I$INCLUDE/src -I$TESTINCLUDE $LIB $TESTLIB $LIBS $TESTLIBS"
$CC $CFLAGS $TESTCFLAGS -o t8dg_tests $TESTSOURCE $SOURCE -I../src -I$INCLUDE -I$INCLUDE/src -I$TESTINCLUDE $LIB $TESTLIB $LIBS $TESTLIBS
